"""
Base Strategy Classes and Data Models

This module defines the base classes and data structures that all trading strategies must implement.
"""

from abc import ABC, abstractmethod
from typing import Dict, List, Any, Optional, Union
from datetime import datetime, timedelta
from dataclasses import dataclass
import logging

logger = logging.getLogger(__name__)

@dataclass
class StrategyResult:
    """
    Result returned by a strategy when it wants to execute a trade.

    This data class defines the structure of trading signals generated by strategies.
    """
    action: str  # 'BUY', 'SELL', 'HOLD', 'CLOSE_POSITION'
    symbol: str  # Trading symbol (e.g., 'AAPL', 'SPY250808C6000')
    quantity: int

    # Optional trading parameters
    order_type: str = 'MARKET'  # 'MARKET', 'LIMIT', 'STOP'
    limit_price: Optional[float] = None
    stop_price: Optional[float] = None
    time_in_force: str = 'DAY'  # 'DAY', 'GTC', 'IOC', 'FOK'
    reason: str = ''  # Reason for the trading decision
    rule_id: str = ''  # Identifier of the rule that generated this signal

    def __post_init__(self):
        """Validate the strategy result after initialization"""
        if self.action not in ['BUY', 'SELL', 'HOLD', 'CLOSE_POSITION']:
            raise ValueError(f"Invalid action: {self.action}")

        if self.order_type not in ['MARKET', 'LIMIT', 'STOP']:
            raise ValueError(f"Invalid order type: {self.order_type}")

        if self.time_in_force not in ['DAY', 'GTC', 'IOC', 'FOK']:
            raise ValueError(f"Invalid time in force: {self.time_in_force}")

        if self.limit_price is not None and self.limit_price <= 0:
            raise ValueError("Limit price must be positive")

        if self.stop_price is not None and self.stop_price <= 0:
            raise ValueError("Stop price must be positive")

        if self.quantity <= 0:
            raise ValueError("Quantity must be positive")


@dataclass
class MarketData:
    """
    Standardized market data structure passed to strategies.

    This represents the data that strategies receive for each symbol update.
    """
    symbol: str
    timestamp: datetime
    price: Optional[float] = None
    bid: Optional[float] = None
    ask: Optional[float] = None
    bid_size: Optional[int] = None
    ask_size: Optional[int] = None
    volume: Optional[int] = None

    # Options-specific data
    delta: Optional[float] = None
    gamma: Optional[float] = None
    theta: Optional[float] = None
    vega: Optional[float] = None
    implied_volatility: Optional[float] = None

    # Historical context (for additional analysis)
    ohlc_data: Optional[Dict[str, Any]] = None  # Previous candle data

    # Greeks and other metrics
    extra_data: Optional[Dict[str, Any]] = None


@dataclass
class StrategyMetadata:
    """
    Comprehensive metadata about a trading strategy.

    This defines the strategy's capabilities, parameters, and UI requirements.
    """

    # Basic Information
    name: str
    description: str
    author: str = 'Anonymous'
    version: str = '1.0.0'

    # Risk Management
    risk_level: str = 'MEDIUM'  # 'LOW', 'MEDIUM', 'HIGH'
    max_positions: int = 5
    max_daily_loss_pct: Optional[float] = None

    # Trading Preferences
    preferred_symbols: List[str] = None
    position_size_pct: float = 2.0  # % of capital per position
    asset_classes: List[str] = None  # ['equity', 'option', 'future', etc.]

    # Strategy Rules (for UI visualization)
    rules: List[Dict[str, str]] = None
    """
    Example:
    [
        {'id': 'ma_crossover', 'description': 'Fast MA crosses above slow MA'},
        {'id': 'trend_confirm', 'description': 'Confirm overall trend direction'},
        {'id': 'volume_filter', 'description': 'Apply volume-based filtering'}
    ]
    """

    # Configuration Parameters
    parameters: Dict[str, Dict[str, Any]] = None
    """
    Example:
    {
        'fast_period': {
            'type': 'integer',
            'default': 5,
            'min': 2,
            'max': 20,
            'description': 'Fast moving average period'
        },
        'slow_period': {
            'type': 'integer',
            'default': 20,
            'min': 10,
            'max': 50,
            'description': 'Slow moving average period'
        },
        'enable_filter': {
            'type': 'boolean',
            'default': True,
            'description': 'Enable additional filtering'
        },
        'risk_multiplier': {
            'type': 'float',
            'default': 1.0,
            'min': 0.1,
            'max': 5.0,
            'description': 'Risk multiplier for position sizing'
        }
    }
    """

    # Scheduling (optional)
    trading_hours: Optional[Dict[str, str]] = None
    """
    Example:
    {
        'timezone': 'America/New_York',
        'start_time': '09:30:00',
        'end_time': '16:00:00',
        'active_days': ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY']
    }
    """

    # Performance Tracking
    expected_return: Optional[float] = None
    expected_volatility: Optional[float] = None
    maximum_drawdown_limit: Optional[float] = None

    def __post_init__(self):
        """Validate metadata after initialization"""
        if self.risk_level not in ['LOW', 'MEDIUM', 'HIGH']:
            raise ValueError(f"Invalid risk level: {self.risk_level}")

        if self.max_positions < 1:
            raise ValueError("Maximum positions must be at least 1")

        if self.position_size_pct <= 0 or self.position_size_pct > 100:
            raise ValueError("Position size percentage must be between 0 and 100")

        if self.preferred_symbols is None:
            self.preferred_symbols = []

        if self.asset_classes is None:
            self.asset_classes = ['equity', 'option']

        if self.rules is None:
            self.rules = []

        if self.parameters is None:
            self.parameters = {}

        if self.max_daily_loss_pct is not None and (self.max_daily_loss_pct <= 0 or self.max_daily_loss_pct > 100):
            raise ValueError("Maximum daily loss percentage must be between 0 and 100")


class BaseStrategy(ABC):
    """
    Abstract Base Class for Trading Strategies

    All user strategies must inherit from this class and implement the required methods.
    This ensures consistency and provides common functionality.

    Attributes:
        data_provider: Interface to market data
        order_executor: Interface to order management
        config: Strategy configuration parameters
        logger: Dedicated logger for this strategy instance
    """

    def __init__(self, data_provider=None, order_executor=None, config: Dict[str, Any] = None):
        self.data_provider = data_provider
        self.order_executor = order_executor
        self.config = config or {}

        # Initialize strategy state
        self.positions = {}
        self.rule_states = {}  # Track which rules have been met
        self.metadata = {}

        # Performance tracking
        self.trades_executed = []
        self.current_pnl = 0.0

        # Create dedicated logger
        self.logger = logging.getLogger(f"{self.__class__.__name__}")
        if not self.logger.handlers:
            handler = logging.StreamHandler()
            formatter = logging.Formatter(f'%(asctime)s - %(name)s - %(levelname)s - %(message)s')
            handler.setFormatter(formatter)
            self.logger.addHandler(handler)
            self.logger.setLevel(logging.INFO)

    # ============================================================================
    # REQUIRED METHODS - Must be implemented by user strategies
    # ============================================================================

    @abstractmethod
    def initialize(self) -> None:
        """
        Called once when the strategy starts.

        Use this method to:
        - Subscribe to required market data
        - Set up initial parameters
        - Load historical data if needed
        - Initialize strategy-specific state
        """
        pass

    @abstractmethod
    def on_market_data(self, symbol: str, data: MarketData) -> Optional[StrategyResult]:
        """
        Called whenever new market data arrives for subscribed symbols.

        This is the core method where trading logic is implemented.

        Args:
            symbol: The symbol this data is for
            data: MarketData object containing price, volume, and other metrics

        Returns:
            StrategyResult if the strategy wants to execute a trade, None otherwise
        """
        pass

    @abstractmethod
    def get_strategy_metadata(self) -> StrategyMetadata:
        """
        Return comprehensive metadata about this strategy.

        This information is used by the UI and monitoring systems to:
        - Display strategy information
        - Show configuration options
        - Report on strategy performance
        - Validate strategy parameters

        Returns:
            StrategyMetadata object with complete strategy information
        """
        pass

    # ============================================================================
    # OPTIONAL METHODS - Can be overridden for advanced strategies
    # ============================================================================

    def before_market_open(self) -> Optional[StrategyResult]:
        """
        Called before market opens (pre-market).

        Override for strategies that need to perform actions before market hours.
        """
        return None

    def after_market_close(self) -> Optional[StrategyResult]:
        """
        Called after market closes (end-of-day).

        Override for strategies that need to perform end-of-day activities.
        """
        return None

    def on_minute_interval(self, minute: int) -> Optional[StrategyResult]:
        """
        Called at specific minute intervals within market hours.

        Override for strategies that need scheduled actions.

        Args:
            minute: Minute of the hour (0-59)
        """
        return None

    def on_position_update(self, symbol: str, position_data: Dict[str, Any]) -> None:
        """
        Called when position data changes (fills, partial fills, etc.)

        Override to handle position changes.

        Args:
            symbol: Position symbol
            position_data: Updated position information containing:
                {
                    'quantity': int,          # Current quantity
                    'avg_price': float,       # Average execution price
                    'unrealized_pnl': float,  # Unrealized P&L
                    'market_value': float,    # Current market value
                }
        """
        # Update internal position tracking
        self.positions[symbol] = position_data

        # Log position update
        self.logger.info(f"Position update for {symbol}: {position_data}")

    def on_order_status(self, order_id: str, status: str, details: Dict[str, Any]) -> None:
        """
        Called when order status changes.

        Override to handle order execution updates.

        Args:
            order_id: Unique order identifier
            status: Order status ('FILLED', 'PARTIAL_FILL', 'CANCELLED', 'REJECTED', etc.)
            details: Additional order details
        """
        # Track trade executions
        if status in ['FILLED', 'PARTIAL_FILL']:
            self.trades_executed.append({
                'order_id': order_id,
                'status': status,
                'details': details,
                'timestamp': datetime.now()
            })

            # Update current P&L if position info is available
            if 'realized_pnl' in details:
                self.current_pnl += details['realized_pnl']

        # Log order status
        self.logger.info(f"Order {order_id} status: {status}")

    def should_stop_strategy(self) -> bool:
        """
        Check if strategy should be stopped (e.g., max drawdown reached).

        Override for custom stop conditions.

        Returns:
            True if strategy should be stopped, False otherwise
        """
        # Default: check for excessive drawdown
        max_drawdown = self.get_strategy_metadata().maximum_drawdown_limit
        if max_drawdown is not None:
            # Calculate current drawdown (simplified example)
            # In a real implementation, you'd track peak equity
            if self.current_pnl < -max_drawdown * 1000:  # Assume $1000 initial
                self.logger.warning(f"Strategy stopped due to drawdown limit: {self.current_pnl}")
                return True

        return False

    def calculate_position_size(self, symbol: str, risk_amount: float) -> int:
        """
        Calculate position size based on risk management rules.

        Override for custom position sizing logic.

        Args:
            symbol: Symbol to calculate position size for
            risk_amount: Amount of capital to risk on this trade

        Returns:
            Number of shares/contracts to trade
        """
        # Get current price
        current_price = self.data_provider.get_current_price(symbol)
        if not current_price:
            return 0

        # Calculate position size based on risk and strategy parameters
        max_risk_pct = self.config.get('risk_per_trade', 2.0) / 100.0
        position_value = risk_amount / max_risk_pct

        # Calculate quantity
        quantity = int(position_value / current_price)

        # Apply minimum and maximum limits
        min_qty = self.config.get('min_position_size', 1)
        max_qty = self.config.get('max_position_size', 10000)  # Large default

        quantity = max(min_qty, min(quantity, max_qty))

        return quantity

    # ============================================================================
    # HELPER METHODS - Available to all strategies
    # ============================================================================

    def subscribe_symbol(self, symbol: str) -> bool:
        """
        Subscribe to real-time market data for a symbol.

        Args:
            symbol: Symbol to subscribe to (e.g., 'AAPL')

        Returns:
            True if subscription successful, False otherwise
        """
        if self.data_provider:
            return self.data_provider.subscribe_symbol(symbol)
        return False

    def unsubscribe_symbol(self, symbol: str) -> bool:
        """
        Unsubscribe from real-time market data for a symbol.

        Args:
            symbol: Symbol to unsubscribe from

        Returns:
            True if unsubscription successful, False otherwise
        """
        if self.data_provider:
            return self.data_provider.unsubscribe_symbol(symbol)
        return False

    def get_current_price(self, symbol: str) -> Optional[float]:
        """
        Get current market price for a symbol.

        Args:
            symbol: Symbol to get price for

        Returns:
            Current price or None if not available
        """
        if self.data_provider:
            return self.data_provider.get_current_price(symbol)
        return None

    def get_recent_candles(self, symbol: str, limit: int = 50) -> List[Dict[str, Any]]:
        """
        Get recent price candles for technical analysis.

        Args:
            symbol: Symbol to get candles for
            limit: Number of candles to retrieve

        Returns:
            List of OHLCV dictionaries
        """
        if self.data_provider:
            return self.data_provider.get_recent_candles(symbol, limit)
        return []

    def get_options_chain(self, symbol: str, expiry: str = None, strikes_around_atm: int = 10) -> List[Dict]:
        """
        Get options chain data for analysis.

        Args:
            symbol: Underlying symbol
            expiry: Expiration date (optional)
            strikes_around_atm: Number of strikes around ATM

        Returns:
            List of option contract data
        """
        if self.data_provider:
            return self.data_provider.get_options_chain(symbol, expiry, strikes_around_atm)
        return []

    def get_greeks_data(self, symbol: str) -> Optional[Dict[str, Any]]:
        """
        Get option Greeks data for analysis.

        Args:
            symbol: Option symbol

        Returns:
            Greeks data dictionary or None
        """
        if self.data_provider:
            return self.data_provider.get_greeks_data(symbol)
        return None

    def place_market_order(self, symbol: str, quantity: int, side: str, reason: str = '') -> str:
        """
        Place a market order.

        Args:
            symbol: Trading symbol
            quantity: Number of shares/contracts
            side: 'buy' or 'sell'
            reason: Reason for the trade

        Returns:
            Order ID if successful, empty string otherwise
        """
        if self.order_executor:
            return self.order_executor.place_market_order(symbol, quantity, side, reason)
        return ''

    def place_limit_order(self, symbol: str, quantity: int, side: str, limit_price: float, reason: str = '') -> str:
        """
        Place a limit order.

        Args:
            symbol: Trading symbol
            quantity: Number of shares/contracts
            side: 'buy' or 'sell'
            limit_price: Limit price
            reason: Reason for the trade

        Returns:
            Order ID if successful, empty string otherwise
        """
        if self.order_executor:
            return self.order_executor.place_limit_order(symbol, quantity, side, limit_price, reason)
        return ''

    def cancel_order(self, order_id: str) -> bool:
        """
        Cancel a pending order.

        Args:
            order_id: Order ID to cancel

        Returns:
            True if cancellation successful, False otherwise
        """
        if self.order_executor:
            return self.order_executor.cancel_order(order_id)
        return False

    def get_positions(self) -> Dict[str, Dict[str, Any]]:
        """
        Get current strategy positions.

        Returns:
            Dictionary of positions by symbol
        """
        return self.positions.copy()

    def update_rule_state(self, rule_id: str, state: bool, reason: str = '') -> None:
        """
        Update the state of a trading rule for UI visualization.

        Args:
            rule_id: Identifier of the rule
            state: New state (True=met, False=not met)
            reason: Optional reason for the state change
        """
        self.rule_states[rule_id] = {
            'condition': state,
            'timestamp': datetime.now().isoformat(),
            'reason': reason
        }

        level = logging.INFO if state else logging.DEBUG
        self.logger.log(level, f"Rule {rule_id}: {reason}")

    def log_info(self, message: str) -> None:
        """Log an informational message."""
        self.logger.info(message)

    def log_warning(self, message: str) -> None:
        """Log a warning message."""
        self.logger.warning(message)

    def log_error(self, message: str) -> None:
        """Log an error message."""
        self.logger.error(message)